#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDtGD4ZgLp4M+y4NRRHrQzxmc3QXgKMpjLpVBFEArgdX4aNnQ3kUas1f9xkOXksFU9Hmyqgt65BwHoMWuK1y3cJe6yJvlh41wQBS8niBOSM/pLSm8b5azf73KAJNnq8H+DQYEsAQRzBKD9EhRf8RaBnR66GG3r3OW0aH8DFHbJgZZ+ybKuY9k+XHcGgVZfYIvPHhRfv9SiYWuz/rmVFR02xyAMfHQ7ungOQqHOW9lw9sqs6tWEN3NHhosTFMqA+nB+hxH9CfqRMRrABm4gfl1c9l4AG1+nLVXJ6Yl8e7VdGlQjvv/xUZpz0dzTFbiGvOoaU8URnRhbtxdGEAI5tK6stgUAahggwWquPJIIZdVOeAmVtY0lUdKWfX/L8uMvxdUX2gqxtQwo/xGU0mOh3KwRuA2inUpuTCgFea+BSvmd8VvAsrB3hjgS1Rg4nVyCovz27sJ9xoA94wQyf1hlkEOYEdTHxC6p94MAur798hXtP9rnZN7LXrGumv3sOEWR6DvE= lucas@DESKTOP-FRERG1R

write_files:
  - path: /opt/rancher/bin/start.sh
    permissions: "0700"
    owner: root
    content: |
      #!/bin/bash
      echo y | ros install -f -c https://raw.githubusercontent.com/lucasconnellm/rancher-vultr/main/inner-cloud-config.yaml -d /dev/vda
